### ISSUE TITLE
Using PHP

### ISSUE THREAD

**Issue by AsherFoster** [AsherFoster/ServerStatus#1]
I'm not exactly a web genius, so the only way I can think of to test a domain's uptime if via a PHP script. Welcome to ideas on how to solve this

**Comment by MrFlash67** [comment]
Node.
I'll try forking it and doing that. There's _probably_ a jQuery way of doing it, but I'll do more server side stuff now.

**Comment by AsherFoster** [comment]
Could you dsze-='=
"

**Comment by AsherFoster** [comment]
Could you make an API at lafol.xyz to do this?

**Comment by MrFlash67** [comment]
Probably.
I'm still working on it, and haven't had much luck with Openshift.

**Comment by MrFlash67** [comment]
@AsherFoster can you assign me to this?

**Comment by AsherFoster** [comment]
Err....

**Comment by MrFlash67** [comment]
Right sidebar?

**Comment by AsherFoster** [comment]
I can only assign myself. If I type your name, it shows "Nothing to show"

**Comment by MrFlash67** [comment]
https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/
Make sure you're using 'MrFlash67"

**Comment by AsherFoster** [comment]
![screen shot 2015-11-30 at 12 57 51 pm](https://cloud.githubusercontent.com/assets/11432528/11461130/0003de60-9762-11e5-9910-164a7f1d9d66.png)

**Comment by MrFlash67** [comment]
You need to be in the issue.

**Comment by AsherFoster** [comment]
![screen shot 2015-11-30 at 12 59 13 pm](https://cloud.githubusercontent.com/assets/11432528/11461147/36dd6faa-9762-11e5-9666-ab067bd5c5be.png)

**Comment by MrFlash67** [comment]
Huh.

**Comment by AsherFoster** [comment]
Fixed. Had to add you as a collaborator

**Comment by AsherFoster** [comment]
Ill delete all this

**Comment by AsherFoster** [comment]
Now using node to check
